### PR TITLE
api/v1: Adds component deletion endpoint and client implementation

### PR DESCRIPTION
**Pull request by joelrebel**
To support deleting server components.

### CODE REVIEW

**Review by JAORMX — CHANGES_REQUESTED** [review]
It's not actually clear to me if this is doing a straight up delete (which is what I think it's doing). Or if we have already some soft-delete logic implemented. @nicolerenee @joelrebel what's your take on enforcing soft-delete logic here? I'd say it would be preferrable.

**Comment by joelrebel** [comment]
> It's not actually clear to me if this is doing a straight up delete (which is what I think it's doing). Or if we have already some soft-delete logic implemented. @nicolerenee @joelrebel what's your take on enforcing soft-delete logic here? I'd say it would be preferrable.

Thats makes sense, thanks for pointing it out. It requires a small schema change https://github.com/volatiletech/sqlboiler#automatic-deletedat-soft-delete . I'd be happy to PR that separately, since it would require its own tests.

 I'm now thinking it would be worth adding soft deletes for the firmware, firmware sets data as well.

**Comment by joelrebel** [comment]
@JAORMX I'll need an approve from you here, the component soft deletes will be added through in a separate PR.

**Comment by joelrebel** [comment]
rebased on main

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
