### PR TITLE
[WIP] Merge all sql files into one

### PR DESCRIPTION
**Pull request by Alva8756**
This is the copy of https://github.com/metal-toolbox/fleetdb/pull/4 for verifying PR `Linting and Test / lint-and-test (pull_request)`

### CODE REVIEW

**Comment by Alva8756** [comment]
I realized we don't have `Linting and Test / lint-and-test (pull_request)` in forked repo.
Reopen this PR for verifying there's no regression.

**Comment by Alva8756** [comment]
Hi @DoctorVin @joelrebel ,
I am reopening this PR for running PR checks since we haven't enabled it in forked repo.

It looks `trivy-container-scan / sec-scan-trivy-1 (pull_request)` reports CVE Vulnerability: `nkeys:v0.4.4`, `otelgin:v0.42.0`, `net:v0.14.0`, `grpc:v1.57.0`.

I am confused that `HEAD` is already using those versions of each libraries. Why it's reporting errors to this PR.
I have tried `re-run` failure tests but it keeps failing.

I am wondering if you see such issues before? Thanks for your help!

**Update**:
I have enabled `Linting and Test / lint-and-test (pull_request)` in forked repo.
`trivy-container-scan` remains disabled due to the warning `This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.`. I am not confident if I can enable it.

**Comment by joelrebel** [comment]
> I have enabled Linting and Test / lint-and-test (pull_request) in forked repo.
trivy-container-scan remains disabled due to the warning This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.. I am not confident if I can enable it.

Lets get these changes merged and, then delete this repo and re-create a new one - so its not a fork?
unless @DoctorVin has other ideas here

**Comment by DoctorVin** [comment]
> > I have enabled Linting and Test / lint-and-test (pull_request) in forked repo.
> > trivy-container-scan remains disabled due to the warning This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.. I am not confident if I can enable it.
> 
> Lets get these changes merged and, then delete this repo and re-create a new one - so its not a fork? unless @DoctorVin has other ideas here

Do we even need this PR in this repo? It's more important for FleetDB, IMO, so that we can get past the DDL issue keeping us at v21 of CrDB? I propose we just close this and confine our work going forward to [fleetDB](https://github.com/metal-toolbox/fleetdb).

**Comment by joelrebel** [comment]
> > > I have enabled Linting and Test / lint-and-test (pull_request) in forked repo.
> > > trivy-container-scan remains disabled due to the warning This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.. I am not confident if I can enable it.
> > 
> > 
> > Lets get these changes merged and, then delete this repo and re-create a new one - so its not a fork? unless @DoctorVin has other ideas here
> 
> Do we even need this PR in this repo? It's more important for FleetDB, IMO, so that we can get past the DDL issue keeping us at v21 of CrDB? I propose we just close this and confine our work going forward to [fleetDB](https://github.com/metal-toolbox/fleetdb).

My apologies for the confusion, for some reason I assumed this PR was on the fleetDB repo. Ignore my comment here.

**Comment by Alva8756** [comment]
Since the PR in the fleetdb already merged, close this PR.
This PR meant to be testing and clarification not to be merge :)

**Pull request closed without merging**
